version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    hostname: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  pwa:
    hostname: ${PWA_STUDIO_PUBLIC_PATH}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./packages/peregrine/.storybook:/usr/src/app/packages/peregrine/.storybook:rw
      - ./packages/peregrine/esm:/usr/src/app/packages/peregrine/esm:rw
      - ./packages/peregrine/scripts:/usr/src/app/packages/peregrine/scripts:rw
      - ./packages/peregrine/src:/usr/src/app/packages/peregrine/src:rw
      - ./packages/pwa-buildpack/src:/usr/src/app/packages/pwa-buildpack/src:rw
      - ./packages/upward-js/lib:/usr/src/app/packages/upward-js/lib:rw
      - ./packages/venia-concept/.storybook:/usr/src/app/packages/venia-concept/.storybook:rw
      - ./packages/venia-concept/esm:/usr/src/app/packages/venia-concept/esm:rw
      - ./packages/venia-concept/src:/usr/src/app/packages/venia-concept/src:rw
      - ./packages/venia-concept/static:/usr/src/app/packages/venia-concept/static:rw
    links:
      - nginx-proxy
    environment:
      VIRTUAL_HOST: ${PWA_STUDIO_PUBLIC_PATH}
      VIRTUAL_PORT: ${PWA_STUDIO_PORTS_DEVELOPMENT}
    expose:
      - ${PWA_STUDIO_PORTS_DEVELOPMENT}
