name: 'Pull Request Labeler'
on:
    - pull_request_target

jobs:
    triage:
        if: ${{github.actor != 'sirugh'}}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/labeler@main
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
